kind: pipeline
name: Kernel Drone

clone:
  depth: 1

steps:
 - name: compile
   image: ubuntu:latest
   environment:
     BOT_API_KEY:
       from_secret: BOT_API_KEY
     CHAT_ID:
       from_secret: CHAT_ID
   commands:
      - apt-get install --no-install-recommends -y -qq aria2 bc bison ca-certificates cpio curl file gcc git lib{c6,c,ssl,xml2}-dev make python3 python3-pip python2 unzip zip wget flex default-jre kmod
      - cd /drone/src
      - bash builder.sh
